name: chromactivity_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - scikit-learn=1.1.3
  - bedtools=2.31.0
  - openjdk=8
  - pip
  - tqdm
  - pybedtools
  - pybigwig
  - loguru
  - joblib
  - ucsc-wigtobigwig
  - ucsc-bigwigtowig
  - pip:
    - -e .
